//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yakuza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumidor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumidor()
        {
            this.Direccion = new HashSet<Direccion>();
        }
    
        public int idConsumidor { get; set; }
        public Nullable<int> idMembresia { get; set; }
        public Nullable<int> idTarjeta { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Membresia Membresia { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion { get; set; }
    }
}
