//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yakuza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumidor
    {
        public int idConsumidor { get; set; }
        public int idMembresia { get; set; }
        public int idTarjeta { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Membresia Membresia { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
