//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yakuza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int IdTag { get; set; }
        public string descripcionTag { get; set; }
        public int IdPlatillo { get; set; }
    
        public virtual Platillo Platillo { get; set; }
    }
}
